name: build-and-test

#on: [push, pull_request]
on:
  push:
    branches:
      - main
      - testscriptwork

jobs:
  build:
    strategy:
      matrix:
        version: ['1.23']
        os: [ubuntu-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: go build

    - name: test
      run: make test

