name: build-and-test
on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.11

      # - name: Build the executables
      #   run: ./mkrel.sh anydb ${{ github.ref_name}}

      # - name: List the executables
      #   run: ls -l ./releases

      # - name: Upload the binaries
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref_name }}
      #     file: ./releases/*
      #     file_glob: true

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## Features",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## Documentation",
                    "labels": ["doc", man"]
                },
                {
                    "title": "## Miscelaneus",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|doc|man|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{steps.github_release.outputs.changelog}}
